### ISSUE TITLE
原稿プレビューでエラー

### ISSUE THREAD

**Issue by kagurazakarasen** [ttrace/vscode-language-japanese-novel#1]
VSCode
バージョン: 1.55.2 (user setup)
OS: Windows_NT x64 10.0.19041

novel-writer拡張バージョン：v0.3.0

で、UTF-8 テキストファイルを原稿プレビューしようとした際（プレビュー設定はデフォルトのまま）
![2021-04-26_12h03_30](https://user-images.githubusercontent.com/26425768/116226045-7fb92700-a78d-11eb-9f4a-8364b2ec96a4.png)
このようなエラーが発生して表示されません。

※Mac環境でも同様のエラーとなりました。

**Comment by ttrace** [comment]
お手数ですが、エラーになる原稿のファイルをアップロードしていただけませんでしょうか。短くて構いません。￼

**Comment by kagurazakarasen** [comment]
[test.txt](https://github.com/ttrace/vscode-language-japanese-novel/files/6384002/test.txt)
本当に単純なテスト用のテキストファイルです。
※改行コードをCRとCRLFの両方でも試してみましたが同様のエラーでした。

**Comment by ttrace** [comment]
こちらでは動いてしまいます。
エクステンションのバージョンを教えていただけませんか？

**Comment by kagurazakarasen** [comment]
![2021-04-28_05h27_42](https://user-images.githubusercontent.com/26425768/116308505-8756eb00-a7e2-11eb-896c-b0aaae5a593d.png)
Version 0.3.0 です。

**Comment by ttrace** [comment]
もしも以前のバージョンを使っていたなら、settings を開き直してみてください。

**Comment by ttrace** [comment]
v0.3.0では再現できなかったのですが、v0.4.0で試してみてください。

**Comment by kagurazakarasen** [comment]
v0.4.0と、v0.4.3で試してみましたが、同様のエラーになります。（インストール後VSCode再起動済み）
また、PDF出力コマンドもためしてみましたが、同じエラーがでてくるようです。

なにか必要なライブラリなどが足りないのでしょうか？
![2021-04-28_18h58_26](https://user-images.githubusercontent.com/26425768/116385498-ce30f900-a853-11eb-983a-8969e3340eb0.png)

**Comment by ttrace** [comment]
それは、たしかにライブラリが足りない感じですね。

**Comment by moriyoshi** [comment]
私の手元でもプレビューでエラーが発生しました。エラーログは以下です。

```
[2021-04-28 20:33:10.248] [exthost] [error] TypeError: userregex.forEach is not a function
    at markUpHtml (/Users/moriyoshi/.vscode/extensions/taiyofujii.novel-writer-0.4.3/extension.js:124:15)
    at editorText (/Users/moriyoshi/.vscode/extensions/taiyofujii.novel-writer-0.4.3/extension.js:116:12)
    at getWebviewContent (/Users/moriyoshi/.vscode/extensions/taiyofujii.novel-writer-0.4.3/extension.js:156:18)
    at verticalpreview (/Users/moriyoshi/.vscode/extensions/taiyofujii.novel-writer-0.4.3/extension.js:34:26)
    at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)
    at S.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:107208)
    at u._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)
    at u._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)
    at u._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)
    at u._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032
    at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
    at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:29750
    at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
    at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
    at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640
    at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
    at acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209
    at Socket.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) Novel.vertical-preview
  ```
  
原因は、

https://github.com/ttrace/vscode-language-japanese-novel/blob/632e1dc/extension.js#L123

この行で取得している `userregex` という設定の値が `settings.json` にないと `undefined` となってしまうためです。

**Comment by ttrace** [comment]
ありがとうございます！
設定がない時でも適切に処理できるようにしておきます。

**Comment by ttrace** [comment]
0.4.6 で配列が空の場合でも正しく処理できるようにしました。ありがとうございます！

**Comment by kagurazakarasen** [comment]
0.4.6で無事に動作するようになりました。
お手数おかけいたしました。早速の対応ありがとうございます。
