### ISSUE TITLE
v0.7.0でプレビューエラー

### ISSUE THREAD

**Issue by kagurazakarasen** [ttrace/vscode-language-japanese-novel#3]
novel-writer v0.7.0 で、縦書きプレビューとサーバー起動どちらもエラーになり表示行えません。

V0.6.4まででは正常にプレビュー表示されていたテキストを使っています。

![2021-05-12_11h51_03](https://user-images.githubusercontent.com/26425768/117913590-967a8480-b31c-11eb-87b3-82caf754707f.png)

環境は
VSCode バージョン: 1.56.1 (user setup)
日付: 2021-05-06T10:08:05.141Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

です。

Novel.preview 周りのsetting.jsonを全削除し、novel-writer拡張をアンインストール、再度インストール、VSCode再起動を行いましたが症状かわらずです。

**Comment by ttrace** [comment]
メニューのView > Output > Log(Extension Host)
の内容を貼り付けていただけると助かります。

**Comment by kagurazakarasen** [comment]
こちらでよろしいでしょうか。

縦書きプレビュー時のエラーログ

[2021-05-12 13:08:16.301] [exthost] [error] Error: Cannot find module 'ws'
Require stack:
- c:\Users\rasen\.vscode\extensions\taiyofujii.novel-writer-0.7.0\extension.ts
- c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.s._load (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:27816)
	at Function.S._load (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:24532)
	at Function.a._load (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:96:58822)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at launchserver (c:\Users\rasen\.vscode\extensions\taiyofujii.novel-writer-0.7.0\extension.ts:45:22)
	at verticalpreview (c:\Users\rasen\.vscode\extensions\taiyofujii.novel-writer-0.7.0\extension.ts:162:13)
	at E._executeContributedCommand (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107932)
	at E.$executeContributedCommand (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:108370)
	at l._doInvokeHandler (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)
	at l._invokeHandler (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)
	at l._receiveRequest (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11187)
	at l._receiveOneMessage (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:9973)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074
	at fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29764
	at fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at t._receiveMessage (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20755)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17641
	at fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at acceptChunk (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12862)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12210
	at Socket.v (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13195)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) Novel.vertical-preview

----
サーバー起動時のエラーログ


[2021-05-12 13:10:39.887] [exthost] [error] Error: Cannot find module 'ws'
Require stack:
- c:\Users\rasen\.vscode\extensions\taiyofujii.novel-writer-0.7.0\extension.ts
- c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.s._load (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:27816)
	at Function.S._load (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:24532)
	at Function.a._load (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:96:58822)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at launchserver (c:\Users\rasen\.vscode\extensions\taiyofujii.novel-writer-0.7.0\extension.ts:45:22)
	at E._executeContributedCommand (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107932)
	at E.$executeContributedCommand (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:108370)
	at l._doInvokeHandler (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)
	at l._invokeHandler (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)
	at l._receiveRequest (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11187)
	at l._receiveOneMessage (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:9973)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074
	at fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29764
	at fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at t._receiveMessage (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20755)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17641
	at fire (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at acceptChunk (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12862)
	at c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12210
	at Socket.v (c:\Users\rasen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13195)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) Novel.launch-preview-server

**Comment by ttrace** [comment]
助かります！
パッケージをやり直した0.7.1をマーケットプレイスに登録しました。

**Comment by ttrace** [comment]
モジュールの入れ忘れ、解消したのでクローズします。
